Content:
    - framework/doc/content
    - modules/rdg/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    name: MOOSE rDG Module
    repo: https://github.com/idaholab/moose
    home: /modules/rdg

Extensions:
    MooseDocs.extensions.appsyntax:
        executable: ${MOOSE_DIR}/modules/rdg
        hide: !include framework/doc/hidden.yml
        remove: !include framework/doc/remove.yml
        includes:
            - framework/include
            - modules/rdg/include
    MooseDocs.extensions.common:
        shortcuts: !include framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include framework/doc/acronyms.yml
