Content:
    - framework/doc/content
    - modules/tensor_mechanics/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    name: MOOSE Tensor_Mechanics Module
    repo: https://github.com/idaholab/moose
    home: /modules/tensor_mechanics

Extensions:
    MooseDocs.extensions.appsyntax:
        executable: ${MOOSE_DIR}/modules/tensor_mechanics
        hide:
            framework: !include framework/doc/hidden.yml
            tensor_mechanics: !include modules/tensor_mechanics/doc/hidden.yml
        remove: !include framework/doc/remove.yml
        includes:
            - framework/include
            - modules/tensor_mechanics/include
    MooseDocs.extensions.common:
        shortcuts: !include framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include framework/doc/acronyms.yml
