Content:
    - framework/doc/content
    - modules/level_set/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    name: MOOSE Level Set Module
    repo: https://github.com/idaholab/moose
    home: /modules/level_set

Extensions:
    MooseDocs.extensions.appsyntax:
        executable: ${MOOSE_DIR}/modules/level_set
        hide: !include framework/doc/hidden.yml
        remove: !include framework/doc/remove.yml
        includes:
            - framework/include
            - modules/level_set/include
    MooseDocs.extensions.common:
        shortcuts: !include framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include framework/doc/acronyms.yml
