Content:
    - framework/doc/content
    - modules/chemical_reactions/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    name: MOOSE Chemical Reactions Module
    repo: https://github.com/idaholab/moose
    home: /modules/chemical_reactions

Extensions:
    MooseDocs.extensions.appsyntax:
        executable: ${MOOSE_DIR}/modules/chemical_reactions
        hide:
            framework: !include framework/doc/hidden.yml
            chemical_reactions: !include modules/chemical_reactions/doc/hidden.yml
        remove: !include framework/doc/remove.yml
        includes:
            - framework/include
            - modules/chemical_reactions/include
    MooseDocs.extensions.common:
        shortcuts: !include framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include framework/doc/acronyms.yml
