Content:
    - framework/doc/content
    - modules/phase_field/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    name: MOOSE Phase Field Module
    repo: https://github.com/idaholab/moose
    home: /modules/phase_field

Extensions:
    MooseDocs.extensions.appsyntax:
        executable: ${MOOSE_DIR}/modules/phase_field
        hide:
            framework: !include framework/doc/hidden.yml
            phase_field: !include modules/phase_field/doc/hidden.yml
        remove: !include framework/doc/remove.yml
        includes:
            - framework/include
            - modules/phase_field/include
    MooseDocs.extensions.common:
        shortcuts: !include framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include framework/doc/acronyms.yml
