Content:
    - framework/doc/content
    - modules/misc/doc/content

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    name: MOOSE Misc Module
    repo: https://github.com/idaholab/moose
    home: /modules/misc

Extensions:
    MooseDocs.extensions.appsyntax:
        executable: ${MOOSE_DIR}/modules/misc
        hide:
            framework: !include framework/doc/hidden.yml
            misc: !include modules/misc/doc/hidden.yml
        remove: !include framework/doc/remove.yml
        includes:
            - framework/include
            - modules/misc/include
    MooseDocs.extensions.common:
        shortcuts: !include framework/doc/globals.yml
    MooseDocs.extensions.acronym:
        acronyms: !include framework/doc/acronyms.yml
